import { IElementProps } from "./type";
export const rawData: Array<IElementProps> = [
  {
    type: "input",
    label: "Opt",
    name: "opt",
    inputType: "number",
    value: "",
    options: [],
  },
  {
    type: "input",
    label: "SwAddr1",
    name: "swAddr1",
    inputType: "text",
    value: "",
    options: [],
  },
  {
    type: "input",
    label: "SwAddr2",
    name: "swAddr2",
    inputType: "text",
    value: "",
    options: [],
  },
  {
    type: "input",
    label: "SwBigo",
    name: "swBigo",
    inputType: "text",
    value: "",
    options: [],
  },
  {
    type: "input",
    label: "SwCaCode",
    name: "swCaCode",
    inputType: "text",
    value: "",
    options: [],
  },
  {
    type: "input",
    label: "swCaName",
    name: "swCaName",
    inputType: "text",
    value: "",
    options: [],
  },
  {
    type: "input",
    label: "swCode",
    name: "swCode",
    inputType: "number",
    value: "",
    options: [],
  },
  {
    type: "input",
    label: "SwDriverNo",
    name: "swDriverNo",
    inputType: "text",
    value: "",
    options: [],
  },
  {
    type: "input",
    label: "SwDriverType",
    name: "swDriverType",
    inputType: "text",
    value: "",
    options: [],
  },
  {
    type: "input",
    label: "swGubun",
    name: "swGubun",
    inputType: "text",
    value: "",
    options: [],
  },
  {
    type: "input",
    label: "SwHp",
    name: "swHp",
    inputType: "text",
    value: "",
    options: [],
  },
  {
    type: "date",
    label: "swIndate",
    name: "swIndate",
    inputType: "",
    value: "",
    options: [],
  },
  {
    type: "date",
    label: "swJdate1",
    name: "swJdate1",
    inputType: "",
    value: "",
    options: [],
  },
  {
    type: "date",
    label: "swJdate2",
    name: "swJdate2",
    inputType: "",
    value: "",
    options: [],
  },
  {
    type: "input",
    label: "swJuminno",
    name: "swJuminno",
    inputType: "text",
    value: "",
    options: [],
  },
  {
    type: "input",
    label: "swName",
    name: "swName",
    inputType: "text",
    value: "",
    options: [],
  },
  {
    type: "input",
    label: "swPaydate",
    name: "swPaydate",
    inputType: "text",
    value: "",
    options: [],
  },
  {
    type: "input",
    label: "swPaykum",
    name: "swPaykum",
    inputType: "number",
    value: "",
    options: [],
  },
  {
    type: "input",
    label: "swPaytype",
    name: "swPaytype",
    inputType: "text",
    value: "",
    options: [],
  },
  {
    type: "input",
    label: "swTel",
    name: "swTel",
    inputType: "text",
    value: "",
    options: [],
  },
  {
    type: "input",
    label: "swWorkOut",
    name: "swWorkOut",
    inputType: "text",
    value: "",
    options: [],
  },
  {
    type: "input",
    label: "swZipcode",
    name: "swZipcode",
    inputType: "text",
    value: "",
    options: [],
  },
];
