export interface IJNOSAUP {
  areaCode: string;
  emailKind: string;
  saupAddr1: string;
  saupAddr2: string;
  saupBigo: string;
  saupCert: string;
  saupDate: string;
  saupEdiEmail: string;
  saupEdiId: string;
  saupEdiPass: string;
  saupEdiSawon: string;
  saupEdiSmsNo: string;
  saupEdiYn: string;
  saupJongmok: string;
  saupJumin: string;
  saupRCode: string;
  saupSajang: string;
  saupSangho: string;
  saupSno: string;
  saupSsno: string;
  saupStamp: string;
  saupStampEs: string;
  saupStampImg: string;
  saupStampImgType: string;
  saupStampQu: string;
  saupStampSe: string;
  saupUptae: string;
  saupZipcode: string;
}

export const emptyObj = {
  areaCode: "",
  emailKind: "",
  saupAddr1: "",
  saupAddr2: "",
  saupBigo: "",
  saupCert: "",
  saupDate: "",
  saupEdiEmail: "",
  saupEdiId: "",
  saupEdiPass: "",
  saupEdiSawon: "",
  saupEdiSmsNo: "",
  saupEdiYn: "",
  saupJongmok: "",
  saupJumin: "",
  saupRCode: "",
  saupSajang: "",
  saupSangho: "",
  saupSno: "",
  saupSsno: "",
  saupStamp: "",
  saupStampEs: "",
  saupStampImg: "",
  saupStampImgType: "",
  saupStampQu: "",
  saupStampSe: "",
  saupUptae: "",
  saupZipcode: "",
};
