export interface IAR110065DETAIL {
  areaCode: string;
  pjCuCode: string;
  pjCuName: string;
  buCode: string;
  buName: string;
  jpKind: string;
  jpSpecific: string;
  pjBigo: string;
  pjDanga: number;
  pjDate: string;
  pjDc: number;
  pjInkum: number;
  pjInkumtype: string;
  pjJago: number;
  pjJpCode: string;
  pjJpName: string;
  pjKumSup: number;
  pjKumVat: number;
  pjKumack: number;
  pjMisukum: number;
  pjQty: number;
  pjReqty: number;
  pjSno: string;
  pjSwCode: string;
  pjSwName: string;
  pjVatDiv: string;
  proxyType: string;
  qtyKg: string;
  qtyL: string;
  queryType: string;
  saleState: string;
  signuser: string;
  pacbCode: string;
}

export const emtObjTab1 = {
  pjDate: "",
  pjJpCode: "",
  pjJpName: "",
  pjQty: 0,
  pjReqty: 0,
  pjDanga: 0,
  pjVatDiv: "",
  pjKumVat: 0,
  pjJago: 0,
  pjKumack: 0,
  pacbCode: "",
  saleState: "",
  proxyType: "",
  buName: "",
  pjInkumtype: "",
  pjInkum: 0,
  pjDc: 0,
  pjMisukum: 0,
  pjSwCode: "",
  pjBigo: "",
  signkey: "",
  signuser: "",
};
