export interface IJNOSAUP {
  areaCode: string;
  opt: number;
  swAddr1: string;
  swAddr2: string;
  swBigo: string;
  swCaCode: string;
  swCaName: string;
  swCode: string;
  swDriverNo: string;
  swDriverType: string;
  swGubun: string;
  swGubunName: string;
  swHp: string;
  swIndate: any;
  swJdate1: any;
  swJdate2: any;
  swJuminno: string;
  swName: string;
  swPaydate: string;
  swPaykum: any;
  swPaytype: string;
  swTel: string;
  swWorkOut: string;
  swZipcode: string;
  cuSeEmail: string;
  mailKind: string;
  eyeSwCode: string;
  swDepartment: string;
  swStampFile: string | null;
  swOutDate: any;
  sgKumack: any;
}
