export interface ICAR {
  areaCode: string;
  areaName: string;
  caBage: string;
  caBageName: string;
  caBco: string;
  caBdamdang: string;
  caBhp: string;
  caBigo: string;
  caBjijum: string;
  caBkYn: string;
  caBldate: string;
  caBman: string;
  caBno: string;
  caBsdate: string;
  caBtel: string;
  caChargeDate: string;
  caCode: string;
  caInDate: string;
  caInsuranceAmt: number;
  caJaegoyn: string;
  caJaegoynName: string;
  caJdate1: string;
  caJdate2: string;
  caManager: string;
  caName: string;
  caRentDate: string;
  caRentYn: string;
  caSafeDate: string;
  caSwCode: string;
  //caSwName: string;
  caType: string;
  caYear: string;
  eyeCarCode: string;
  caAmt: number;
  caDiscountM: number;
  caMAmt: number;
  caDiscountAmt: number;
}

export const emptyObj = {
  areaCode: "",
  areaName: "",
  caAmt: 0,
  caBage: "",
  caBageName: "",
  caBco: "",
  caBdamdang: "",
  caBhp: "",
  caBigo: "",
  caBjijum: "",
  caBkYn: "",
  caBldate: "",
  caBldateT: "",
  caBman: "",
  caBno: "",
  caBsdate: "",
  caBtel: "",
  caChargeDate: "",
  caCode: "",
  caDiscountAmt: 0,
  caDiscountM: 0,
  caInDate: "",
  caInsuranceAmt: 0,
  caJaegoyn: "",
  caJaegoynName: "",
  caJdate1: "",
  caJdate2: "",
  caMAmt: 0,
  caManager: "",
  caName: "",
  caRentDate: "",
  caRentYn: "",
  caSafeDate: "",
  caSwCode: "",
  //caSwName: "",
  caType: "",
  caYear: "",
  eyeCarCode: "",
};
