export interface ICM110065 {
  //tab1
  cuJpJaego: number;
  custIn: string;
  custOut: string;
  jcCycle: number;
  jcDangaName: string;
  jcDangaType: string;
  jcJpCode: string;
  jcJpDandate: null;
  jcJpDanga: number;
  jcJpName: string;
  jcJpSpec: string;
  jcJpState: string;
  jcLastdate5: string;
  jcVatKind: string;
  jcVatName: string;
  jpOutdanga: number;
  jpSort: number;
  jpStateName: string;
  queryType: string;

  //tab2
  cuCircuitDate: string;
  cuFinishDate: string;
  cuMTransmCd: string;
  cuMeterLr: string;
  cuMeterLrName: string;
  cuMeterM3: number;
  cuMeterTurm: string;
  cuMeterTurmName: string;
  cuMeterType: string;
  cuMeterTypeName: string;
  cuNo: string;
  cuRh2o: string;
  cuSajang: string;
  cuSangho: string;
  cuSvKumack: number;
  cuTankName: string;
  cuTankYn: string;
  //   queryType: string; //davhtsaj bgaa uchraas hasav
  gasifyCheckDate1: string;
  gasifyCheckDate2: string;
  gasifyCo1: string;
  gasifyCo2: string;
  gasifyMakeDate1: string;
  gasifyMakeDate2: string;
  gasifyPower1: string;
  gasifyPower2: string;
  gasifySno1: string;
  gasifySno2: string;
  gasifyVol1: string;
  gasifyVol2: string;
  //   queryType: string;
  seq: number;
  tankCuCd1: string;
  tankCuCd2: string;
  tankFirstDate1: string;
  tankFirstDate2: string;
  tankInsideDate1: string;
  tankInsideDate2: string;
  tankMakeCo1: string;
  tankMakeCo2: string;
  tankMakeDate1: string;
  tankMakeDate2: string;
  tankMakeSno1: string;
  tankMakeSno2: string;
  tankMax1: string;
  tankMax2: string;
  tankOutsideDate1: string;
  tankOutsideDate2: string;
  tankRcv1: string;
  tankRcv2: string;
  tankSno1: string;
  tankSno2: string;
  tankTransmCd1: string;
  tankTransmCd2: string;
  tankVol1: string;
  tankVol2: string;

  //tab3
  cuBigo1: string;
  cuBigo2: string;
  cuMemo: string;
  cuRdanga: number;
  cuRdangaType: string;
  cuRdangaTypeName: string;
  //   cuRh2o: string;
  //   queryType: string;
  acctNo: string;
  bankName: string;
  cmsAcctno: string;
  cmsAppdt: string;
  cmsBanknm: string;
  cmsDepositor: string;
  cmsGubun: string;
  cmsState: string;
  depositor: string;
  //   queryType: string;
  //   seq: number;
}
